### PR TITLE
CLIMATE-776 - Update conda dependencies

### PR DESCRIPTION
**Pull request by jarifibrahim**

### CODE REVIEW

**Comment by Omkar20895** [comment]
Hello @jarifibrahim, to my knowledge we have numpy 1.11.0 and h5py 2.6.0 available and are pretty stable versions. If we are going to update the dependencies why not update them to the latest stable versions? Please correct me if I am wrong. Your thoughts are welcome. Thanks. 

@lewismc please take a look at this. If its :+1: from you then we can merge it. Thanks.

**Comment by Omkar20895** [comment]
With this addressed we can close #318  and get going with the VM, the work was stalled because of conflicting dependencies during the installation on the VM.

**Comment by jarifibrahim** [comment]
@Omkar20895 Basemap does not work with numpy 1.11.0. It requires numpy 1.10* . I'll update h5py to 2.6.0.

**Comment by Omkar20895** [comment]
Ohh I didn't knew it. Anyways thanks for letting me know 👍

**Comment by jarifibrahim** [comment]
@Omkar20895 @lewismc Please merge this branch ASAP. The travis-ci build is failing because of conflicting dependencies.

**Comment by lewismc** [comment]
@Omkar20895 can you please merge?

**Comment by Omkar20895** [comment]
Yeah! I will do it in an hour.

**Comment by Omkar20895** [comment]
Done :)

**Comment by lewismc** [comment]
Thank you

On Thu, Apr 7, 2016 at 11:10 AM, Omkar <notifications@github.com> wrote:

> Done :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/climate/pull/324#issuecomment-207032739>
>



-- 
*Lewis*

**Comment by jarifibrahim** [comment]
Thank you @lewismc @Omkar20895.
Please take a look at the PR for [ubuntu-install.sh](https://github.com/apache/climate/pull/318) and 
[utils_tests](https://github.com/apache/climate/pull/322). The travis-ci build also depends on these two PRs.

**Pull request merged**
