### PR TITLE
CLIMATE-379 - Allows dataset customisation

### PR DESCRIPTION
**Pull request by Omkar20895**
This patch allows the user to customise the name of the local dataset that is being uploaded in the web-app.

### CODE REVIEW

**Comment by Omkar20895** [comment]
hey @lewismc @MJJoyce, please have a look at this patch.

**Comment by lewismc** [comment]
I am +1, any comments @MJJoyce ?

**Comment by MJJoyce** [comment]
:+1:

**Comment by lewismc** [comment]
Please commit @Omkar20895

**Comment by Omkar20895** [comment]
I haven't been granted the write access to the repository yet. right??

**Comment by lewismc** [comment]
No you have, the canonical source is here
https://git-wip-us.apache.org/repos/asf/climate.git
The Github code is merely a mirror and is not the canonical source as it is
not hosted at the Apache Software Foundation.
The link above is hosted at the ASF and therefore canonical.
Thanks
Lewis

On Wed, Jan 27, 2016 at 9:38 AM, Omkar <notifications@github.com> wrote:

> I haven't been granted the write access to the repository yet. right??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/climate/pull/276#issuecomment-175762787>.
>



-- 
*Lewis*

**Pull request merged**
