### PR TITLE
CLIMATE-825 - Coalesce data sources into one module

### PR DESCRIPTION
**Pull request by agoodm**
-Added a new class called `DatasetLoader`
-Added corresponding documentation and unit tests

Read the docstrings for more info on the API, but the gist of it is that it was designed to easily load the inputs to each data source loader from our current config files.

This is intended for the 1.2 release.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
@agoodm can you please fix landscape.io issues? The build failed because there were multiple PEP8 violations. Please take a look at this -> [Link](https://landscape.io/diff/413629)

**Comment by agoodm** [comment]
@jarifibrahim I fixed the PEP8 violations flagged in my previous commits, but the landscape.io check has been running for over 12 hours.

**Comment by jarifibrahim** [comment]
@agoodm I'm not sure why the build is stuck. I tried starting a new build but it also got stuck at `waiting`. The issue seems to be with landscape. Please go ahead and merge this PR.

**Comment by huikyole** [comment]
@agoodm This is wonderful. Thank you so much. I have very minor suggestions.
- dataset_loader.py can be located in ocw/data_source folder.
- Would it be possible to have 1) multiple references and 2) reference only without targets?
1) is very useful when calculating metrics using multiple variables. 
2) for example, we should be able to load daily reanalysis data only and calculate k-means clustering.

**Comment by agoodm** [comment]
@huikyole Not sure if I agree with your first suggestion. I thought the intent of having data_source as a separate directory was originally due to having multiple modules for loading from each data source. The modules in the base ocw directory represent each of the individual steps in the workflow, eg dataset processing, running evaluations, and plotting. The main thing that was missing previously was loading the datasets which is exactly what this module aims to do. So for now I think leaving it here is appropriate. I think @lewismc should share his thoughts on this though too.

I absolutely agree with your second suggestion though. I originally had it set up this way because to my recollection, the rest of the OCW codebase (particularly metrics and evaluations) were designed with "one reference" dataset. Given that Loikith et al. 2013 uses two reanalysis datasets, we should get rid of this rigid assumption not only for `dataset_loader.py` but potentially for `evaluation.py` as well. I think for now changing  the former obviously takes precedence but we should consider exploring the the latter as well.

**Pull request merged**
