### PR TITLE
CLIMATE-760 - Address documentation warnings

### PR DESCRIPTION
**Pull request by jarifibrahim**
- Fix configuration_writer import error
- Update table of contents tree

### CODE REVIEW

**Comment by lewismc** [comment]
@jarifibrahim does this fix all of the errors shown in the Jira issues description at CLIMATE-760?

**Comment by jarifibrahim** [comment]
@lewismc I was unable to reproduce all the errors in the Jira issue. I just pulled from the master branch and fixed all the issues that the documentation had.

**Comment by lewismc** [comment]
After pulling in your fix I am getting the following
```
lmcgibbn@LMC-032857 /usr/local/climate/docs(master) $ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.1
loading pickled environment... done
WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [100%] data_source/data_sources
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_GPM_IMERG_files:13: ERROR: Unexpected indentation.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_GPM_IMERG_files:1: ERROR: Unknown interpreted text role "list".
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_GPM_IMERG_files:1: ERROR: Unknown interpreted text role "list".
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_GPM_IMERG_files:14: WARNING: Block quote ends without a blank line; unexpected unindent.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_NLDAS_forcingA_files:14: ERROR: Unexpected indentation.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_NLDAS_forcingA_files:1: ERROR: Unknown interpreted text role "list".
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_NLDAS_forcingA_files:1: ERROR: Unknown interpreted text role "list".
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_NLDAS_forcingA_files:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_WRF_2d_files:14: ERROR: Unexpected indentation.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_WRF_2d_files:1: ERROR: Unknown interpreted text role "list".
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_WRF_2d_files:1: ERROR: Unknown interpreted text role "list".
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_WRF_2d_files:15: WARNING: Block quote ends without a blank line; unexpected unindent.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_WRF_2d_files_RAIN:10: ERROR: Unexpected indentation.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_WRF_2d_files_RAIN:1: ERROR: Unknown interpreted text role "list".
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_WRF_2d_files_RAIN:11: WARNING: Block quote ends without a blank line; unexpected unindent.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_dataset_from_multiple_netcdf_files:8: ERROR: Unexpected indentation.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_dataset_from_multiple_netcdf_files:9: WARNING: Block quote ends without a blank line; unexpected unindent.
/usr/local/climate/ocw/data_source/local.py:docstring of local.load_dataset_from_multiple_netcdf_files:21: ERROR: Unknown interpreted text role "list".
```
I'll fix these issues later on today and commit. Thanks
Lewis

**Comment by jarifibrahim** [comment]
@lewismc I'm not getting any such errors. I'm using sphinx 1.3.6
```
docs[CLIMATE-760] % make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.6
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] config/config_writer                                  
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                  
generating indices... genindex http-routingtable py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.
```

**Pull request merged**
