### PR TITLE
CLIMATE-556 - Changes in easy_install scripts : creates new virtualenv by prompting the user for permission.

### PR DESCRIPTION
**Pull request by Omkar20895**
Added a patch which enables the user to grant permission for creating a new virtualenv when the user runs the easy-install scripts in easy-cow.

### CODE REVIEW

**Comment by lewismc** [comment]
Good job @Omkar20895 thank you for submitting your patch.
I am having some issues, please see the attachment which indicates some issues with the patch. When I run it I get the following
```
lmcgibbn@LMC-032857 /usr/local/climate(master) $ ./easy-ocw/install-osx.sh

---------------------------------------------------------------------------
                         Welcome to Easy OCW
---------------------------------------------------------------------------

./easy-ocw/install-osx.sh: line 235: syntax error: unexpected end of file
```
screen shot 2015-10-26 at 10 08 59 am
You can see the presence of the line ending producing errors.
If you could address the issues with an updated PR it would be fantastic? If you could also squash your commit history it would be fantastic... this just keeps the Git commit log cleaner.

**Comment by Omkar20895** [comment]
I forgot to close one of the if statements I ll send the patch once again. I cant find a way to squash my commit history and I would be grateful if you could help me with it.

**Comment by lewismc** [comment]
@Omkar20895 thanks for reply
> I forgot to close one of the if statements I ll send the patch once again.
No problems, if you want to update this pull request that would be fine
> I cant find a way to squash my commit history and I would be grateful if you could help me with it.
No problems, there you go https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by Omkar20895** [comment]
I have updated the pull request, run it and let me know if there is any trouble.

**Comment by Omkar20895** [comment]
thanks for the link, it helped!

**Comment by lewismc** [comment]
Hi @Omkar20895 , I like the new coloured guidance for the terminal prompts. There seems to be some issue thought with the terminal logging. When I run the osx script, there is no logging to stdout. This is not ideal as it is very useful to understand what is going on. Can you take a look into it? I see the following
screen shot 2015-10-26 at 1 02 01 pm

**Comment by Omkar20895** [comment]
Hello lewis, I have updated the pull request and sorry there were so many errors in the patch. I just hope there aren't any now. I am also attaching the screenshot of the results that I have got.
screen shot 2015-10-27 at 2 49 36 am
 
Thanks.

**Comment by lewismc** [comment]
Hi @Omkar20895 
I pulled a new version of the patch and I am still having problems logging the output to the terminal.
For example, if you run the install-osx.sh script as follows
```
./install-osx.sh -e
```
Then when prompted, press 'Y', after I enter 'Y' I see no logging output to the terminal at all.
Can you please try this yourself and see if you can reproduce what I am describing?

**Comment by Omkar20895** [comment]
Hi @lewismc 
According to my new version of the patch when you enter ./install-osx.sh -e it should not prompt for a yes or no. 
If you enter ./install-osx.sh then it prompts the user for a yes or no. The above mentioned functionality is working in my pc,I am unable to figure out why it is not working in your pc please check it once again and also refer to the image that I have attached earlier so that you can get a more clear idea of what I am trying to say. 
 
Thank you!

**Comment by lewismc** [comment]
@Omkar20895 I get what you are saying... however I do not see any evidence of log output streaming into the terminal. That is my issue.

**Comment by Omkar20895** [comment]
Hi @lewismc can you specify your os details because I have run the script so many times on OS X and it shows me the output log with all the executing commands. I am attaching a new screenshot with all the output log in the terminal.
screen shot 2015-11-04 at 2 03 37 am

Thanks.

**Comment by lewismc** [comment]
@MJJoyce can you please check this patch out on your local copy of OCW?
@Omkar20895 I am running on OSX 10.9.5 with iTerm terminal. I've also tried it out with the system terminal and cannot get the output you have posted. I hope it is something local to me and that we can merge but need some QA from someone else.

**Comment by Omkar20895** [comment]
@lewismc that would be great! :)

**Comment by MJJoyce** [comment]
Sure @lewismc, let me catch up and scope

**Comment by MJJoyce** [comment]
So I commented out the various install commands so I didn't blow out my existing environment, so I may be mistaken, but it looks like it's working as expected for me @lewismc. Log output for the various commands should stream out to an install_log file, so you shouldn't be seeing everything show up on your terminal.

**Comment by lewismc** [comment]
That sounds excellent. +1 yo commit those code. Thank you for code review.

On Sunday, November 8, 2015, Michael Joyce <notifications@github.com> wrote:

> So I commented out the various install commands so I didn't blow out my
> existing environment, so I may be mistaken, but it looks like it's working
> as expected for me @lewismc <https://github.com/lewismc>. Log output for
> the various commands should stream out to an install_log file, so you
> shouldn't be seeing everything show up on your terminal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/climate/pull/255#issuecomment-154835355>.
>


-- 
*Lewis*

**Comment by Omkar20895** [comment]
hello @lewismc can you merge the snippet now?? 
@MJJoyce thanks for the code review. :)

**Comment by lewismc** [comment]
Yes will do it when I get wifi, sorry just got this.

On Tuesday, November 10, 2015, Omkar20895 <notifications@github.com> wrote:

> hello @lewismc <https://github.com/lewismc> can you merge the snippet
> now??
> @MJJoyce <https://github.com/MJJoyce> thanks for the code review. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/climate/pull/255#issuecomment-155437421>.
>


-- 
*Lewis*

**Comment by lewismc** [comment]
Thanks @Omkar20895 for the patch here. Thanks for for verifying everything OK.

**Comment by Omkar20895** [comment]
Thank you. @lewismc

**Comment by Omkar20895** [comment]
Hello @lewismc there was a code discrepancy in merging this pull request with the main branch. I think this was due to some tech error while fetching the updated pull request and this might be the reason why the code was not running as expected in your local machine. The code merged is not the same code from the pull request that I have updated above. I apologise beforehand if the mistake was from my side. I have sent a new pull request #269 please have a look at it and verify it.
Thanks

**Comment by lewismc** [comment]
@Omkar20895 you've closed that issue off!

**Pull request closed without merging**
