### PR TITLE
CLIMATE - 950 Convert Readme.md to reStructured Text

### PR DESCRIPTION
**Pull request by prateekiiest**
Jira Issue https://issues.apache.org/jira/browse/CLIMATE-950?jql=project%20%3D%20CLIMATE%20AND%20component%20%3D%20documentation

This will remove the errors while uploading to pypi platform

### CODE REVIEW

**Comment by prateekiiest** [comment]
@lewismc @huikyole reviews please

**Comment by prateekiiest** [comment]
the readme is updated

**Comment by lewismc** [comment]
Excellent @prateekiiest  I will merge

**Comment by prateekiiest** [comment]
Thanks @lewismc for merging this in

**Pull request merged**
