### PR TITLE
CLIMATE-725 Ensure that OCW 1.1 Test PyPi Works as Expected

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses https://issues.apache.org/jira/browse/CLIMATE-725
The remainder of the comment can be found over there and I am also going to augment the release procedure to accommodate publishing of OCW to the Cheeseshop.

### CODE REVIEW

**Comment by lewismc** [comment]
@huikyole if you get time can you verify this patch please?

**Comment by huikyole** [comment]
@lewismc I will test it after installing Ubuntu linux. Thanks a lot!

**Comment by Omkar20895** [comment]
@lewismc just out of curiosity I went ahead and tried this patch. It worked successfully and I was able to import to all the packages mentioned in this commit in a python session. :) 
Thanks.

**Comment by lewismc** [comment]
Thanks @Omkar20895 I am going to commit this

**Pull request merged**
