### PR TITLE
CLIMATE-508: added a class 'Downscaling' and histogram plots

### PR DESCRIPTION
**Pull request by huikyole**

### CODE REVIEW

**Comment by cgoodale** [comment]
Hey @huikyole I was looking into the open issues and I saw this one and I have to agree with @MJJoyce  that example code would be great.  Even a simple example of how the API you defined in the class would be called.

From what I see in the code I "think" it would be something like the following:

# the basic way a user would import the Class
>>> from ocw.statistical_downscaling import Downscaling
# simple class instantiation
>>> my_downscaler = Downscaling(ref, present, future)
# Then we use the defined downscaler to return values
>>> downscaled_present, modeled_future = my_downscaler.Delta_addition()
>>> 

Am I even close here?  Perhaps a unittest would also help convey how the code would be used.

I am not sure I know enough about Downscaling, but all the return documentation is the same:
:returns: downscaled model_present and model_future

**Comment by kwhitehall** [comment]
@MJJoyce @cgoodale  @huikyole  @chrismattmann  This is great functionality to have in the code base which been demonstrated to work. It has been outstanding here for quite sometime. As for the most part it is an additional file and a couple updates the plotter class. Would anyone be adverse to merging this code as is, then dev-ing out the outstanding issues in separate issue tickets?

**Comment by MJJoyce** [comment]
Would have been nice if the requests/questions had been answered, or even just acknowledged in some way, before merging. But if you want to take on the responsibility of cleaning it up and documenting it properly in the code you won't hear much complaining from me! :+1:

**Comment by huikyole** [comment]
I have been waiting for #111 to be merged before working on #112.

**Comment by MJJoyce** [comment]
Is there some dependency here @huikyole? It doesn't look like it to me, but perhaps I'm overlooking it. Or was there some other reason to wait to address this before looking into the other one? The integration of this one would be way less work since the other breaks the build where as this one doesn't touch anything old in the codebase.

**Comment by huikyole** [comment]
@MJJoyce, there is dependency. Current OCW time parsing module could not properly handle my test data (CMIP5 model output). Once #111 is merged, I will refactor this one and provide an example.

**Comment by MJJoyce** [comment]
Alrighty. No reason to hold merging this then if it's just the example data not in this PR that wouldn't load. +1 again from me @kwhitehall. Easy enough to integrate the example(s) that @huikyole has later once we fix up and merge #111

**Comment by kwhitehall** [comment]
@huikyole I looked through this code, but I don't see the dependency to  #111 that you refer.
If it is a dependency that is wrapped up in an example, then I would suggest the following:
(1) we can go ahead and merge this (PR#112) as is. 
(2) given the nature of  #111 I wonder if you couldn't leverage the existing function in utils.py called calc_climatology_season to achieve the functionality you desire. 
(3) provide an example for how to use this current functionality.

**Comment by kwhitehall** [comment]
Resolve CLIMATE-508. Merged PR#112.

**Comment by kwhitehall** [comment]
@huikyole Please close this PR.

**Comment by huikyole** [comment]
I still wonder why we prioritize the changes in #112 over major bug in the time decoding and seasonal average. Some critical bugs in calc_climatology_season in utils.py were discussed and resolved two years ago in one of the subversion hosted on a JPL server. Why does every dataset need to have time dimension whose length is a multiple of 12 to calculate its seasonal average?

**Comment by MJJoyce** [comment]
That sounds like a question for the relevant pull request @huikyole. I would move that discussion over there and close this pull request since it's been merged.

Thanks much

**Comment by chrismattmann** [comment]
Everyone it's closed by commiting something saying this closes #112 anyone can close it on the PMC

**Comment by MJJoyce** [comment]
Ack @chrismattmann. Looks like there was a typo in the merge commit that caused it to not close.

**Comment by kwhitehall** [comment]
Ack @chrismattmann  and @MJJoyce. Thanks for the advice, still learning!

**Comment by MJJoyce** [comment]
NP @kwhitehall. We can just include a reference to this in a future merge commit if @huikyole doesn't beat us to closing it. Easy peasy.

**Comment by chrismattmann** [comment]
Yep no worries I just call them tickle commits change spacing on s text file then add commit msg all good!

**Pull request closed without merging**
