### PR TITLE
CLIMATE-561 Prompts the user for a destination directory to install the ocw virtaulenv.

### PR DESCRIPTION
**Pull request by Omkar20895**
Hello @lewismc I have tried to squash the commits as you mentioned in the previous pull request but I got some weird results with it and it would be great if you can help me with it.

### CODE REVIEW

**Comment by MJJoyce** [comment]
Hey @Omkar20895, are you up to date when you're making the branch? Looks like you're a bit behind master perhaps

**Comment by Omkar20895** [comment]
Sorry, my mistake. @MJJoyce

**Comment by MJJoyce** [comment]
Hey @Omkar20895,

You've got some merge related stuff in here and a few other things that we could clean up a bit. Can you clean this up a bit. Try a rebase off master with

```rebase -i master``` 

after you've checked out your feature branch and squash out some of these commits. This will also help you get rid of the historical commits that we don't need to see in this diff.

**Comment by Omkar20895** [comment]
Hello @MJJoyce can you please cancel my pull request?? I have messed up my fork repository of ocw and I am unable to revert it. I will fork the repo again, apply the changes and send in a new pull request.
Thanks.

**Comment by MJJoyce** [comment]
Hey Omkar, i can't actually close the pull request, however you should be able to close it since you opened it.

**Pull request closed without merging**
