### PR TITLE
Climate-561 Prompts the user for a destination directory to install t…

### PR DESCRIPTION
**Pull request by Omkar20895**
…he ocw virtaulenv.

### CODE REVIEW

**Comment by lewismc** [comment]
@Omkar20895 you've closed this issue off?

**Comment by Omkar20895** [comment]
No, this pull request is active. The previous pull request with ticket #255 got clumsy with unnecessary commits and got corrupted in my local fork so I closed it and reopened it again here. Sorry for the inconvenience.

**Comment by Omkar20895** [comment]
Thank you guys @lewismc and @MJJoyce for bearing with me though I am a novice to the open source development :) I also wanted to ask one more thing, I am on my winter vacation now and I wanted to work on this project more. So can you guys please point me at some issues that I could work on??

**Comment by lewismc** [comment]
@Omkar20895 the mailing list is the best place for this kind of thing. We will see you on there.
Thnk you

**Pull request closed without merging**
