### PR TITLE
CLIMATE-914 - Update dataset_processor.spatial_regrid module

### PR DESCRIPTION
**Pull request by huikyole**
- map_coordinates has been replaced with scipy.interpolate.griddata.

### CODE REVIEW

**Comment by huikyole** [comment]
@agoodm Could you please go over the changes?

**Comment by agoodm** [comment]
@huikyole Looks like your changes don't work for 2D latlon arrays, as per CI build logs:

```
======================================================================
ERROR: test_two_dimensional_lats_lons (ocw.tests.test_dataset_processor.TestSpatialRegrid)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/apache/climate/ocw/tests/test_dataset_processor.py", line 399, in test_two_dimensional_lats_lons
    self.input_dataset, self.new_lats, self.new_lons)
  File "/home/travis/build/apache/climate/ocw/dataset_processor.py", line 278, in spatial_regrid
    new_values_temp = griddata((lons[mask_index], lats[mask_index]), values_original[mask_index],
IndexError: index 2 is out of bounds for axis 0 with size 2
```

Given that regridding is probably one of the largest bottlenecks in our RCMES workflows, I think it is also worth profiling both this version (once the above error is fixed) and the old map_coordinates version to see if there are any performance impacts, since the spatial_regridding tests seem to be running more slowly.

**Comment by huikyole** [comment]
Thank you for the quick review, @agoodm. In the previous commit, I forgot the nosetests.
- test_two_dimensional_lats_lons does not make any sense. If latitudes and longitudes are two-dimensional, their shape must be [nY, nX]. I cannot understand why the module had reshaped one-dimensional latitudes and longitudes.
- We can never trade off accuracy against efficiency. There is no documentation why map_coordinates outputs -9999 without mask. I do not think addressing this bottleneck is our top priority.

**Comment by agoodm** [comment]
No worries, I definitely agree that simply getting the correct result is more important. I just think it should be looked into in the future, especially if the slowdown proves to be significant for the longer examples.

For now though:  :+1:

**Pull request merged**
