### PR TITLE
[CLIMATE - 957] Include Absolute Biasing under Metrics

### PR DESCRIPTION
**Pull request by prateekiiest**
Fixes issue https://issues.apache.org/jira/browse/CLIMATE-957

### CODE REVIEW

**Comment by prateekiiest** [comment]
@lewismc could you have a look at it?

**Comment by lewismc** [comment]
@prateekiiest can you please provide a Unit test?

**Comment by prateekiiest** [comment]
sure @lewismc , I will add a test soon

**Comment by prateekiiest** [comment]
Added test for this

**Comment by prateekiiest** [comment]
@lewismc could you please make a review. I will add further changes if required

**Comment by lewismc** [comment]
+1, @prateekiiest thank you

**Comment by prateekiiest** [comment]
Thanks @lewismc

**Pull request merged**
