### PR TITLE
CLIMATE-762 Automate the linking of the frontend directory from the backend directory.

### PR DESCRIPTION
**Pull request by MichaelArthurAnderson**
CLIMATE-762 

- Automate the linking of the frontend directory from the backend directory.

### CODE REVIEW

**Comment by lewismc** [comment]
If we can separate these PR's into individual ones then I think we can begin to merge some of your contributions into master @MichaelArthurAnderson thank you

**Comment by MichaelArthurAnderson** [comment]
@lewismc I see four separate branches and pull requests in my git.  

Are you seeing a single big request?

https://github.com/apache/climate/pull/465
https://github.com/apache/climate/pull/468
https://github.com/apache/climate/pull/469
https://github.com/apache/climate/pull/470

https://github.com/MichaelArthurAnderson/climate/tree/CLIMATE-762
https://github.com/MichaelArthurAnderson/climate/tree/CLIMATE-917
https://github.com/MichaelArthurAnderson/climate/tree/CLIMATE-826
https://github.com/MichaelArthurAnderson/climate/tree/CLIMATE-940

**Comment by lewismc** [comment]
Hi @MichaelArthurAnderson yes I am seeing 7 changed files and 4 commits. Is this intended? I think you may have merged them into each other.

**Comment by lewismc** [comment]
Note that the TravisCI test only fails on Python 2.7 which is fine as it is related to the Pydap dependency.

**Pull request closed without merging**
