### PR TITLE
CLIMATE-610 - Example scripts for multi model use and subregion uses

### PR DESCRIPTION
**Pull request by kwhitehall**

### CODE REVIEW

**Comment by MJJoyce** [comment]
Hey Kim,

Thanks for the Pull Request! Can you please update the title and commit message with the reference to the ticket that this is addressing?

Also, we tend to not commit binary files since they tend to cause unneeded bloat. Are all the plots that you added generated by the scripts? If they are I think we can safely remove them and let users generate them if they need them.

Thoughts?

**Comment by kwhitehall** [comment]
Acknowledge @MJJoyce. Yes the plots are those generated by the scripts. We can remove them, no worries. I'll update.

**Comment by MJJoyce** [comment]
Hey Kim, I had to rebase and squash this fixing commit in so you'll have to close this one manually. Sorry for the inconvenience =/

**Comment by kwhitehall** [comment]
Np @MJJoyce. Sorry to have put you through the extra work!

**Pull request closed without merging**
