### PR TITLE
optimizing traversing

### PR DESCRIPTION
**Pull request by Kejia**
use a set to track visiting state. also some minor updates.

### CODE REVIEW

**Comment by lewismc** [comment]
I just checked and these build failures have nothing to do with the proposed patch. They are dependency related.. I assume they failed due to network issue on build machines.

**Comment by lewismc** [comment]
@Kejia did you succesffuly run this with sample MCC-related data?

**Comment by Kejia** [comment]
hi @lewismc: no, i didn't run this with sample MCC-related data. it seems the test failure is related to the package `netcdf4'. not sure about the root cause.

**Comment by lewismc** [comment]
Yeah, the failure is intermittent and OK for the time being. @kwhitehall can you try this patch out?

**Comment by lewismc** [comment]
@Kejia can you please update this PR to resolve conflict? Thank you in advance.

**Pull request merged**
