### PR TITLE
CLIMATE-877 Adding PODAAC data source to OCW GUI

### PR DESCRIPTION
**Pull request by Omkar20895**
- This PR adds PODAAC to OCW GUI.
- This PR will be updated until the community is satisfied with the code addition.
- Right now this is just a template that I have created and I will be adding updates as soon as I hack the code.
- Please don't test this PR until I ask for it, since it is gonna be unstable for a while.

Thanks. :)

### CODE REVIEW

**Comment by lewismc** [comment]
This is a good start. Let me know when you want code review.

**Comment by lewismc** [comment]
@Omkar20895 if I were you, I would attempt to address https://issues.apache.org/jira/browse/CLIMATE-886 and then get the tests passing for the frontend. Once we have it stable again then we can think about adding new data sources.

**Comment by Omkar20895** [comment]
Yes sure, I did not notice this issue, I will work on it. Thanks for the heads up!

**Comment by Omkar20895** [comment]
This PR did not affect the master branch in any way, I am going to open a new one. I did not close this PR, it was merged automatically due to this PR #418

**Pull request merged**
