### PR TITLE
CLIMATE-626 Update doc strings in Downscaling class

### PR DESCRIPTION
**Pull request by MichaelArthurAnderson**
CLIMATE-626 Update doc strings in Downscaling class

- Added missing docstrings.
- Updated documentation templates.
- Pylinted Downscaling class.

### CODE REVIEW

**Comment by lewismc** [comment]
+1 @MichaelArthurAnderson please push to remote master

**Comment by MichaelArthurAnderson** [comment]
@lewismc I don't think I have permission to push to the master.  I believe I only have RO access.

**Comment by MichaelArthurAnderson** [comment]
Confirmed I do not have RW.

**Comment by lewismc** [comment]
Hi @MichaelArthurAnderson I just checked our private@ mailing list archives and this was because in the past you chose not to join the project as a committer and PMC member. Has your situation changed and are you able to now accept the INVITATION? If you would like I can forward you the email and we can take it from there. The OCW PMC has already VOTE'd to extend the invitation so it's merely just a case of accepting it. Thanks

**Comment by MichaelArthurAnderson** [comment]
That would be great!

**Pull request merged**
