### PR TITLE
CLIMATE-785 - RCMED.py: optimize code

### PR DESCRIPTION
**Pull request by jarifibrahim**
Fixes https://issues.apache.org/jira/browse/CLIMATE-785

### CODE REVIEW

**Comment by lewismc** [comment]
ok to test

**Comment by lewismc** [comment]
+1 please merge @jarifibrahim

**Comment by jarifibrahim** [comment]
@lewismc The builds for the PR's aren't working right now. The code is built only after it is merged to master branch. I've raised a JIRA ticket and it should be fixed soon.

**Comment by lewismc** [comment]
Can you post the Jira ticket here please?

**Comment by jarifibrahim** [comment]
[INFRA-11783 Add Github integration to jenkins](https://issues.apache.org/jira/browse/INFRA-11783)

**Comment by lewismc** [comment]
+1 @jarifibrahim please commit to master branch

**Pull request merged**
