### PR TITLE
Climate-798 - Redundant code in evaluation.py

### PR DESCRIPTION
**Pull request by jarifibrahim**

### CODE REVIEW

**Comment by huikyole** [comment]
@jarifibrahim The codes in 'evaluation.py' are not redundant. Sometimes, the metrics calculation result is a single number whose dimension (ndim) equals zero. Please do not commit the changes and keep the original 'evaluation.py'.

**Comment by jarifibrahim** [comment]
@huikyole Please take a look at this image

**Comment by huikyole** [comment]
Hi Ibrahim,

The ndim can be zero in the attached case.

[cid:image001.png@01D1D048.C1C12B60]

Thanks,
Kyo

**Comment by jarifibrahim** [comment]
@huikyole The link to the image in your comment is broken. Please fix it.

**Comment by huikyole** [comment]
Sorry, @jarifibrahim 
screen shot 2016-06-27 at 7 50 48 am

**Comment by jarifibrahim** [comment]
@huikyole Thank you so much. Closing PR because of **Invalid Issue**.

**Pull request closed without merging**
