### PR TITLE
CLIMATE-766 Easy-ocw/install-ubuntu.sh script is broken

### PR DESCRIPTION
**Pull request by jarifibrahim**
Can anyone please test this script and post the results.
I have not tested it. I didn't want to mess with my installation.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
@MichaelArthurAnderson @lewismc Could you please test this script?

**Comment by lewismc** [comment]
Hi @jarifibrahim what's the current status of this patch?

**Comment by jarifibrahim** [comment]
@lewismc The script works fine. But there's a dependency issue. Is there a wiki page that lists the dependencies ? The existing `ocw-conda-dependency` file has conflicting dependencies.

**Comment by lewismc** [comment]
@jarifibrahim this issue has been merged... right? If so can you close off?

**Comment by jarifibrahim** [comment]
@lewismc No. This issue has not been merged.

**Comment by Omkar20895** [comment]
So I was just wondering if all the conflicts in the dependencies are solved? If they are, just let me know. The VM has been delayed for too long and we haven't released 1.1 yet. :)

**Comment by lewismc** [comment]
In all honesty there is no biggie on the VM, that can come together
whenever. Releases are the primary thing to focus on.
I'm going to kick of a release discussion.

On Saturday, April 9, 2016, Omkar <notifications@github.com> wrote:

> So I was just wondering if all the conflicts in the dependencies are
> solved? If they are, just let me know. The VM has been delayed for too long
> and we haven't released 1.1 yet. :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/climate/pull/318#issuecomment-207793570>
>


-- 
*Lewis*

**Comment by jarifibrahim** [comment]
@Omkar20895 All dependency conflicts have been resolved.

**Comment by lewismc** [comment]
Ibrahim can you please post successful TravisCI build link here?

On Saturday, April 9, 2016, Ibrahim Jarif <notifications@github.com> wrote:

> @Omkar20895 <https://github.com/Omkar20895> All dependency conflicts have
> been resolved.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/climate/pull/318#issuecomment-207812290>
>


-- 
*Lewis*

**Comment by jarifibrahim** [comment]
Here's the latest [build](https://travis-ci.org/jarifibrahim/climate/builds/121927729).

Btw the Travis-CI does not use the install-ubuntu.sh script to install OCW (Check .travis.yml file). The script has some prompts which cannot be handled on Travis-CI.

**Comment by lewismc** [comment]
We need to set up a build on builds.apache.org that builds only on Ubuntu
machines and uses the install-ubuntu script which also answers the prompts.
We should maybe consider a docker deployment for this. I suppose this will
all be part of your GSoC project of it IRS ahead Ibrahim. Exciting days
ahead

On Saturday, April 9, 2016, Ibrahim Jarif <notifications@github.com> wrote:

> Here's the latest build
> <https://travis-ci.org/jarifibrahim/climate/builds/121927729>.
>
> Btw the Travis-CI does not use the install-ubuntu.sh script to install OCW
> (Check .travis.yml file). The script has some prompts which cannot be
> handled on Travis-CI.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/climate/pull/318#issuecomment-207815116>
>


-- 
*Lewis*

**Comment by jarifibrahim** [comment]
Yes Lewis. Exciting days ahead :dancers:

**Pull request merged**
