### PR TITLE
CLIMATE-793 - Update install-ubuntu.sh script

### PR DESCRIPTION
**Pull request by jarifibrahim**
- Merge install-ubuntu.sh and install-conda.sh
- Delete install-conda.sh
- Delete conda_environment.txt

### CODE REVIEW

**Comment by jarifibrahim** [comment]
The Jenkins build is failing due to some permission issues with the conda installation.

The script works fine on a bare machine.
Please check this build for confirmation => [https://travis-ci.org/jarifibrahim/climate/builds/133594864](https://travis-ci.org/jarifibrahim/climate/builds/133594864)

The Travis-demo branch has this branch plus the CLIMATE-794 branch.

**Comment by lewismc** [comment]
Why are you proposing to remove the files?

**Comment by jarifibrahim** [comment]
* conda_environment.txt file is useless.
* install-conda.sh can be merged to install-ubuntu.sh to improve the process of installation. The user has to run only one script to install everything. Currently user has to run install-ubuntu.sh, close the current terminal, start a new terminal and execute conda-install.sh file.

**Comment by lewismc** [comment]
@jarifibrahim ack please merge to master

**Pull request merged**
