### PR TITLE
CLIMATE-863 - Address warning, etc within Travis-CI log output

### PR DESCRIPTION
**Pull request by jarifibrahim**

### CODE REVIEW

**Comment by lewismc** [comment]
I've tested this locally and the test output is looking much cleaner. I am +1 to merge into master.

**Comment by lewismc** [comment]
@jarifibrahim can you please update this PR and resolve the merge conflict? Thank you

**Comment by jarifibrahim** [comment]
@lewismc Done.

**Comment by jarifibrahim** [comment]
The travis build is failing due to some random issue. See this build https://travis-ci.org/jarifibrahim/climate/builds/174863520

**Comment by lewismc** [comment]
ACK, please merge into master

**Pull request merged**
