### PR TITLE
CLIMATE-889 - Fix Travis Build

### PR DESCRIPTION
**Pull request by jarifibrahim**
- Skip test if unable to download the dataset

### CODE REVIEW

**Comment by agoodm** [comment]
Is this a good idea? I could see this leading to potentially inconsistent testing behavior... though I suppose in practice it probably doesn't matter that much since we probably won't be making too many changes to the dap loader in the future. Since the failures right now are consistent, it means that the problem is something the opendap team needs to fix on their end. I have been in contact with them but we haven't been able to get this resolved yet.

**Comment by jarifibrahim** [comment]
The bug/exceptions are not in ocw but in its dependencies. The downloading of the dataset is handled by the respective packages. So if something goes wrong while downloading the datasets that means the issue is with the package that downloads it and not with ocw. The tests are skipped only if we are not able to retrieve the dataset. Once the dataset is downloaded all the succeeding tests will execute normally.

**Comment by agoodm** [comment]
Right... but that does not mean there will be inherently nothing wrong with the rest of the test, since having access to these datasets is a prerequisite. What would we do then if we eventually make changes to the dap loader that have some sort of bugs, but don't notice them because the opendap test server is down as it is now and the tests falsely pass? I get that it is annoying to have constant build failures that aren't our fault, but at the very least I can is that the failures at least force you to investigate the logs. Conversely I fear that this would lead to us being less likely to check the build logs in the scenario I mention above since if you don't, you'd have know way of knowing that those tests were actually skipped.

**Comment by jarifibrahim** [comment]
Right. That would happen. Maybe we could temporarily skip these tests.
Once opendap servers are working we could add these tests back.

**Comment by lewismc** [comment]
I'm +1 for merging this into master folks. Heads up, we've just updated Pydap for Python 3.X support and will be releasing a new version shortly. I think making the basic check and handling the exception is fine in this case. stabilizing the test is more important just now as it means we can drive towards an OC release.

**Comment by agoodm** [comment]
An update: The opendap test server should be up again, and we have fixed the issues on the podaac side of things as well with the next release of that.

Anyway I am ok with merging this, but please keep the reservations mentioned in my previous post in mind. Once a python 3 build of pydap is available on conda-forge, we'll need to make sure these tests don't get skipped.

**Comment by jarifibrahim** [comment]
@agoodm @lewismc I've added some comments to the exception handling. Should I merge it now?

**Comment by lewismc** [comment]
+1

**Comment by agoodm** [comment]
@jarifibrahim Can you remove these changes for podaacpy but keep them for pydap? Opendap support is still working on resolving problems on their end so we will probably need to skip those tests for a little:

https://opendap.atlassian.net/servicedesk/customer/portal/1/SUP-20

**Comment by jarifibrahim** [comment]
@agoodm Done via https://github.com/apache/climate/commit/6156eff08b11f92acbfee0ca5be5d78e473483c6

**Pull request merged**
