### PR TITLE
CLIMATE-643 - Updating some of examples

### PR DESCRIPTION
**Pull request by huikyole**
Not only the bias calculation example, CLI has been debugged and updated. Some modules have been added to the dataset_processor to propagate missing value information.

### CODE REVIEW

**Comment by MJJoyce** [comment]
@huikyole,

83717b2 isn't updating an example. That's changing the CLI. This should get moved to a different ticket so as not to confuse the two things. Similarly, the changes in 88d9c22 aren't just touching examples. They're also touching the CLI. And changes in 03f5b2c are changing dataset_processor stuff. Can we please separate this out into logical tickets.

Also can you please update the Title of the PR to be in line with the specification in the wiki? It has to be CLIMATE-<version number> otherwise it doesn't always mirror to JIRA properly.

**Comment by huikyole** [comment]
@MJJoyce  I understand your concerns. However, updating examples was impossible without adding new modules to the dataset_processor. CLI is also using the code based on examples. I will try to separate these into three tickets.

**Comment by MJJoyce** [comment]
If the changes build off one another just separate them out into different feature branches and merge/rebase according during the dev work. Otherwise we end up with overly complicated pull requests that address multiple tickets and that just makes reviews and integration more challenging. Small, atomic changes are always easier. If you need help with the branching/merging let me know. I'm more than happy to show you a few easy ways to take care of this!

**Comment by MJJoyce** [comment]
To give you an idea of what I'm talking about here @huikyole in case it's confusing. Here's an example of how I would have broken these down into multiple tickets and their relevant changes.

New Ticket 1:
This [new function](https://github.com/apache/climate/pull/210/files#diff-e41b7ee3c7e3b2339c964f6882ecfaa5R426) would be here. 
This [variable name update](https://github.com/apache/climate/pull/210/files#diff-e41b7ee3c7e3b2339c964f6882ecfaa5R409) is related so we could include that as well.
Tests for the new function would be included in a commit in here as well.

New Ticket 2:
Missing data [changes](https://github.com/apache/climate/pull/210/files#diff-e41b7ee3c7e3b2339c964f6882ecfaa5R463) would fall in another ticket here.
Tests for this new function would be here as well.

New Ticket 3:
[This is a propagation bug](https://github.com/apache/climate/pull/210/files#diff-e41b7ee3c7e3b2339c964f6882ecfaa5R463) for the existing values and would be its own ticket.
New test would be included in here as well so we don't miss this bug in the future!

New Ticket 4:
Any change in [the CLI app](https://github.com/apache/climate/pull/210/files#diff-9e183b82ea6b20fcfefa86ca818c670eR19) that you have in here would be in another ticket.
Would probably need to update tests if appropriate for the CLI (I'm not familiar w/ the code so I'm unsure if that's the case)

This ticket:
The changes in [examples/knmi_to_cru31_full_bias.py](https://github.com/apache/climate/pull/210/files#diff-a84c6055f2eee6f83c3eac5d00e324d0R28) would be in this ticket since it's the actual update to the example file.

---

So, if these tickets build off of each other you would do something to the effect of:
* Make feature branch off master for Ticket 1. Make changes, update tests, and make PR
* Make feature branch off master for Ticket 2. Make changes, update tests, and make PR. When we merge Ticket 1/2 we will need to rebase this but that should be fine. The changes are obvious enough to make merging and issues easy/trivial.
* Make feature branch for Ticket 3 off master. Make changes, write test, and make PR. Will need to rebase here as well when we merge but see above. Should be easy.
* Make feature branch for Ticket 4 off master. Etc.
* Make feature branch for this ticket. You will probably need to merge some of the stuff in the ticket 1, 2, and 3 feature branches in here so that way you have the changes that you need. When we merge the others into master it's simple enough to rebase again and include those relevant commits.

---

Hopefully that helps. If you have questions let me know!

**Pull request closed without merging**
